// Package SSIMP provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package mock

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Credential defines model for credential.
type Credential struct {
	Context           *[]string `json:"@context,omitempty"`
	CredentialSubject *struct {
		Id           *string       `json:"id,omitempty"`
		Name         *string       `json:"name,omitempty"`
		Prescription *Prescription `json:"prescription,omitempty"`
	} `json:"credentialSubject,omitempty"`
	ExpirationDate *string `json:"expirationDate,omitempty"`
	IssuanceDate   *string `json:"issuanceDate,omitempty"`
	Issuer         *struct {
		Id   *string `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"issuer,omitempty"`
	Proof *CredentialProof `json:"proof,omitempty"`
	Type  *[]string        `json:"type,omitempty"`
}

// CredentialProof defines model for credentialProof.
type CredentialProof struct {
	Created            *string `json:"created,omitempty"`
	Jws                *string `json:"jws,omitempty"`
	ProofPurpose       *string `json:"proofPurpose,omitempty"`
	Type               *string `json:"type,omitempty"`
	VerificationMethod *string `json:"verificationMethod,omitempty"`
}

// Drug defines model for drug.
type Drug struct {
	DrugName           *string      `json:"drugName,omitempty"`
	DrugNumber         *float32     `json:"drugNumber,omitempty"`
	DrugType           *string      `json:"drugType,omitempty"`
	Info               *interface{} `json:"info,omitempty"`
	RefillAvailability *bool        `json:"refillAvailability,omitempty"`
}

// Error defines model for error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// OintmentDrugInfo defines model for ointmentDrugInfo.
type OintmentDrugInfo struct {
	AmountOfMedicine     *float32 `json:"amountOfMedicine,omitempty"`
	ApplicationFrequency *string  `json:"applicationFrequency,omitempty"`
	Usage                *string  `json:"usage,omitempty"`
	UseArea              *string  `json:"useArea,omitempty"`
}

// Prescription defines model for prescription.
type Prescription struct {
	Drugs        *[]Drug `json:"drugs,omitempty"`
	HospitalInfo *struct {
		DoctorName               *string  `json:"doctorName,omitempty"`
		DoctorSignatureStamp     *string  `json:"doctorSignatureStamp,omitempty"`
		HospitalName             *string  `json:"hospitalName,omitempty"`
		Location                 *string  `json:"location,omitempty"`
		MedicalInstitutionNumber *float32 `json:"medicalInstitutionNumber,omitempty"`
		Phone                    *string  `json:"phone,omitempty"`
		PrefectureNumber         *float32 `json:"prefectureNumber,omitempty"`
		ScoreVoteNumber          *float32 `json:"scoreVoteNumber,omitempty"`
	} `json:"hospitalInfo,omitempty"`
	IssuanceInfo *struct {
		ExpirationDate *string `json:"expirationDate,omitempty"`
		IssuanceDate   *string `json:"issuanceDate,omitempty"`
	} `json:"issuanceInfo,omitempty"`
	PatientInfo *struct {
		Birthday *string `json:"birthday,omitempty"`
		Name     *string `json:"name,omitempty"`
		Sex      *string `json:"sex,omitempty"`
	} `json:"patientInfo,omitempty"`
}

// Presentation defines model for presentation.
type Presentation struct {
	Context              *[]string            `json:"@context,omitempty"`
	Proof                *[]PresentationProof `json:"proof,omitempty"`
	Type                 *string              `json:"type,omitempty"`
	VerifiableCredential *[]Credential        `json:"verifiableCredential,omitempty"`
}

// PresentationProof defines model for presentationProof.
type PresentationProof struct {
	Challenge          *string `json:"challenge,omitempty"`
	Created            *string `json:"created,omitempty"`
	Jws                *string `json:"jws,omitempty"`
	ProofPurpose       *string `json:"proofPurpose,omitempty"`
	Type               *string `json:"type,omitempty"`
	VerificationMethod *string `json:"verificationMethod,omitempty"`
}

// TabletDrugInfo defines model for tabletDrugInfo.
type TabletDrugInfo struct {
	DaysOfMedication     *float32 `json:"daysOfMedication,omitempty"`
	NumberOfDoses        *string  `json:"numberOfDoses,omitempty"`
	NumberOfDrug         *float32 `json:"numberOfDrug,omitempty"`
	TimingToTakeMedicine *string  `json:"timingToTakeMedicine,omitempty"`
}

// PostDoctorsDoctorIdPrescriptionsCredentialOffersJSONBody defines parameters for PostDoctorsDoctorIdPrescriptionsCredentialOffers.
type PostDoctorsDoctorIdPrescriptionsCredentialOffersJSONBody struct {
	Issuer *struct {
		Id   *string `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"issuer,omitempty"`
	Medicines *[]string `json:"medicines,omitempty"`
}

// PostPatientsPatientIdPrescriptionsCredentialsJSONBody defines parameters for PostPatientsPatientIdPrescriptionsCredentials.
type PostPatientsPatientIdPrescriptionsCredentialsJSONBody struct {
	CredentialOfferId *string `json:"credentialOfferId,omitempty"`
	Did               *string `json:"did,omitempty"`
	Jws               *string `json:"jws,omitempty"`
}

// PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayloadJSONBody defines parameters for PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload.
type PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayloadJSONBody struct {
	Challenge          *string `json:"challenge,omitempty"`
	VerificationMethod *string `json:"verificationMethod,omitempty"`
}

// PostPatientsPatientIdPrescriptionsPresentationsJSONBody defines parameters for PostPatientsPatientIdPrescriptionsPresentations.
type PostPatientsPatientIdPrescriptionsPresentationsJSONBody struct {
	CredentialId          *string `json:"credentialId,omitempty"`
	JwsSignature          *string `json:"jwsSignature,omitempty"`
	PresentationRequestId *string `json:"presentationRequestId,omitempty"`
	VerificationMethod    *string `json:"verificationMethod,omitempty"`
}

// PostDoctorsDoctorIdPrescriptionsCredentialOffersJSONRequestBody defines body for PostDoctorsDoctorIdPrescriptionsCredentialOffers for application/json ContentType.
type PostDoctorsDoctorIdPrescriptionsCredentialOffersJSONRequestBody PostDoctorsDoctorIdPrescriptionsCredentialOffersJSONBody

// PostPatientsPatientIdPrescriptionsCredentialsJSONRequestBody defines body for PostPatientsPatientIdPrescriptionsCredentials for application/json ContentType.
type PostPatientsPatientIdPrescriptionsCredentialsJSONRequestBody PostPatientsPatientIdPrescriptionsCredentialsJSONBody

// PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayloadJSONRequestBody defines body for PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload for application/json ContentType.
type PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayloadJSONRequestBody PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayloadJSONBody

// PostPatientsPatientIdPrescriptionsPresentationsJSONRequestBody defines body for PostPatientsPatientIdPrescriptionsPresentations for application/json ContentType.
type PostPatientsPatientIdPrescriptionsPresentationsJSONRequestBody PostPatientsPatientIdPrescriptionsPresentationsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates credential offer for prescription (generates a link for QR code)
	// (POST /doctors/{doctorId}/prescriptions/credential-offers/)
	PostDoctorsDoctorIdPrescriptionsCredentialOffers(ctx echo.Context, doctorId string) error
	// Gets credential offer by id
	// (GET /doctors/{doctorId}/prescriptions/credential-offers/{credentialOfferId})
	GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferId(ctx echo.Context, doctorId string, credentialOfferId string) error
	// Gets credential issued for given credential offer
	// (GET /doctors/{doctorId}/prescriptions/credential-offers/{credentialOfferId}/credential)
	GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferIdCredential(ctx echo.Context, doctorId string, credentialOfferId string) error
	// Gets all dids belonging to given patient
	// (GET /patients/{patientId}/dids)
	GetPatientsPatientIdDids(ctx echo.Context, patientId string) error
	// Gets all prescription credentials issued for given patient
	// (GET /patients/{patientId}/prescriptions/credentials)
	GetPatientsPatientIdPrescriptionsCredentials(ctx echo.Context, patientId string) error
	// Creates credential in response to credential offer from doctor
	// (POST /patients/{patientId}/prescriptions/credentials/)
	PostPatientsPatientIdPrescriptionsCredentials(ctx echo.Context, patientId string) error
	// Gets prescription credential by id issued for given patient
	// (GET /patients/{patientId}/prescriptions/credentials/{credentialId})
	GetPatientsPatientIdPrescriptionsCredentialsCredentialId(ctx echo.Context, patientId string, credentialId string) error
	// Generates canonical jws payload of credential presentaion for signing
	// (POST /patients/{patientId}/prescriptions/credentials/{credentialId}/presentation-jws-payload)
	PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload(ctx echo.Context, patientId string, credentialId string) error
	// Creates verifiable presentation in response to prescription presentation request from pharmacy
	// (POST /patients/{patientId}/prescriptions/presentations/)
	PostPatientsPatientIdPrescriptionsPresentations(ctx echo.Context, patientId string) error
	// Creates presentation request for prescription (generates link for a QR code)
	// (POST /pharmacies/{pharmacyId}/prescriptions/presentation-requests)
	PostPharmaciesPharmacyIdPrescriptionsPresentationRequests(ctx echo.Context, pharmacyId string) error
	// Gets presentation request for prescription by request id
	// (GET /pharmacies/{pharmacyId}/prescriptions/presentation-requests/{presentationRequestId})
	GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestId(ctx echo.Context, pharmacyId string, presentationRequestId string) error
	// Gets verifiable presentation for given presentation request
	// (GET /pharmacies/{pharmacyId}/prescriptions/presentation-requests/{presentationRequestId}/presentation)
	GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestIdPresentation(ctx echo.Context, pharmacyId string, presentationRequestId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostDoctorsDoctorIdPrescriptionsCredentialOffers converts echo context to params.
func (w *ServerInterfaceWrapper) PostDoctorsDoctorIdPrescriptionsCredentialOffers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "doctorId" -------------
	var doctorId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "doctorId", runtime.ParamLocationPath, ctx.Param("doctorId"), &doctorId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter doctorId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostDoctorsDoctorIdPrescriptionsCredentialOffers(ctx, doctorId)
	return err
}

// GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferId converts echo context to params.
func (w *ServerInterfaceWrapper) GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "doctorId" -------------
	var doctorId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "doctorId", runtime.ParamLocationPath, ctx.Param("doctorId"), &doctorId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter doctorId: %s", err))
	}

	// ------------- Path parameter "credentialOfferId" -------------
	var credentialOfferId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "credentialOfferId", runtime.ParamLocationPath, ctx.Param("credentialOfferId"), &credentialOfferId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter credentialOfferId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferId(ctx, doctorId, credentialOfferId)
	return err
}

// GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferIdCredential converts echo context to params.
func (w *ServerInterfaceWrapper) GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferIdCredential(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "doctorId" -------------
	var doctorId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "doctorId", runtime.ParamLocationPath, ctx.Param("doctorId"), &doctorId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter doctorId: %s", err))
	}

	// ------------- Path parameter "credentialOfferId" -------------
	var credentialOfferId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "credentialOfferId", runtime.ParamLocationPath, ctx.Param("credentialOfferId"), &credentialOfferId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter credentialOfferId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferIdCredential(ctx, doctorId, credentialOfferId)
	return err
}

// GetPatientsPatientIdDids converts echo context to params.
func (w *ServerInterfaceWrapper) GetPatientsPatientIdDids(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "patientId" -------------
	var patientId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "patientId", runtime.ParamLocationPath, ctx.Param("patientId"), &patientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter patientId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPatientsPatientIdDids(ctx, patientId)
	return err
}

// GetPatientsPatientIdPrescriptionsCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GetPatientsPatientIdPrescriptionsCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "patientId" -------------
	var patientId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "patientId", runtime.ParamLocationPath, ctx.Param("patientId"), &patientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter patientId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPatientsPatientIdPrescriptionsCredentials(ctx, patientId)
	return err
}

// PostPatientsPatientIdPrescriptionsCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) PostPatientsPatientIdPrescriptionsCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "patientId" -------------
	var patientId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "patientId", runtime.ParamLocationPath, ctx.Param("patientId"), &patientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter patientId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostPatientsPatientIdPrescriptionsCredentials(ctx, patientId)
	return err
}

// GetPatientsPatientIdPrescriptionsCredentialsCredentialId converts echo context to params.
func (w *ServerInterfaceWrapper) GetPatientsPatientIdPrescriptionsCredentialsCredentialId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "patientId" -------------
	var patientId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "patientId", runtime.ParamLocationPath, ctx.Param("patientId"), &patientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter patientId: %s", err))
	}

	// ------------- Path parameter "credentialId" -------------
	var credentialId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "credentialId", runtime.ParamLocationPath, ctx.Param("credentialId"), &credentialId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter credentialId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPatientsPatientIdPrescriptionsCredentialsCredentialId(ctx, patientId, credentialId)
	return err
}

// PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload converts echo context to params.
func (w *ServerInterfaceWrapper) PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "patientId" -------------
	var patientId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "patientId", runtime.ParamLocationPath, ctx.Param("patientId"), &patientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter patientId: %s", err))
	}

	// ------------- Path parameter "credentialId" -------------
	var credentialId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "credentialId", runtime.ParamLocationPath, ctx.Param("credentialId"), &credentialId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter credentialId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload(ctx, patientId, credentialId)
	return err
}

// PostPatientsPatientIdPrescriptionsPresentations converts echo context to params.
func (w *ServerInterfaceWrapper) PostPatientsPatientIdPrescriptionsPresentations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "patientId" -------------
	var patientId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "patientId", runtime.ParamLocationPath, ctx.Param("patientId"), &patientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter patientId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostPatientsPatientIdPrescriptionsPresentations(ctx, patientId)
	return err
}

// PostPharmaciesPharmacyIdPrescriptionsPresentationRequests converts echo context to params.
func (w *ServerInterfaceWrapper) PostPharmaciesPharmacyIdPrescriptionsPresentationRequests(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pharmacyId" -------------
	var pharmacyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "pharmacyId", runtime.ParamLocationPath, ctx.Param("pharmacyId"), &pharmacyId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pharmacyId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostPharmaciesPharmacyIdPrescriptionsPresentationRequests(ctx, pharmacyId)
	return err
}

// GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestId converts echo context to params.
func (w *ServerInterfaceWrapper) GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pharmacyId" -------------
	var pharmacyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "pharmacyId", runtime.ParamLocationPath, ctx.Param("pharmacyId"), &pharmacyId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pharmacyId: %s", err))
	}

	// ------------- Path parameter "presentationRequestId" -------------
	var presentationRequestId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "presentationRequestId", runtime.ParamLocationPath, ctx.Param("presentationRequestId"), &presentationRequestId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter presentationRequestId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestId(ctx, pharmacyId, presentationRequestId)
	return err
}

// GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestIdPresentation converts echo context to params.
func (w *ServerInterfaceWrapper) GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestIdPresentation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "pharmacyId" -------------
	var pharmacyId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "pharmacyId", runtime.ParamLocationPath, ctx.Param("pharmacyId"), &pharmacyId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pharmacyId: %s", err))
	}

	// ------------- Path parameter "presentationRequestId" -------------
	var presentationRequestId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "presentationRequestId", runtime.ParamLocationPath, ctx.Param("presentationRequestId"), &presentationRequestId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter presentationRequestId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestIdPresentation(ctx, pharmacyId, presentationRequestId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/doctors/:doctorId/prescriptions/credential-offers/", wrapper.PostDoctorsDoctorIdPrescriptionsCredentialOffers)
	router.GET(baseURL+"/doctors/:doctorId/prescriptions/credential-offers/:credentialOfferId", wrapper.GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferId)
	router.GET(baseURL+"/doctors/:doctorId/prescriptions/credential-offers/:credentialOfferId/credential", wrapper.GetDoctorsDoctorIdPrescriptionsCredentialOffersCredentialOfferIdCredential)
	router.GET(baseURL+"/patients/:patientId/dids", wrapper.GetPatientsPatientIdDids)
	router.GET(baseURL+"/patients/:patientId/prescriptions/credentials", wrapper.GetPatientsPatientIdPrescriptionsCredentials)
	router.POST(baseURL+"/patients/:patientId/prescriptions/credentials/", wrapper.PostPatientsPatientIdPrescriptionsCredentials)
	router.GET(baseURL+"/patients/:patientId/prescriptions/credentials/:credentialId", wrapper.GetPatientsPatientIdPrescriptionsCredentialsCredentialId)
	router.POST(baseURL+"/patients/:patientId/prescriptions/credentials/:credentialId/presentation-jws-payload", wrapper.PostPatientsPatientIdPrescriptionsCredentialsCredentialIdPresentationJwsPayload)
	router.POST(baseURL+"/patients/:patientId/prescriptions/presentations/", wrapper.PostPatientsPatientIdPrescriptionsPresentations)
	router.POST(baseURL+"/pharmacies/:pharmacyId/prescriptions/presentation-requests", wrapper.PostPharmaciesPharmacyIdPrescriptionsPresentationRequests)
	router.GET(baseURL+"/pharmacies/:pharmacyId/prescriptions/presentation-requests/:presentationRequestId", wrapper.GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestId)
	router.GET(baseURL+"/pharmacies/:pharmacyId/prescriptions/presentation-requests/:presentationRequestId/presentation", wrapper.GetPharmaciesPharmacyIdPrescriptionsPresentationRequestsPresentationRequestIdPresentation)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPauBb+Kx7t/XDvDMTgdJOUTzclfYFtA0nYZKaZzB1hH0DUllxJDmEy/Pc7km1s",
	"Y5k4Tdg22f0G1tvROc9z9BzL98hlQcgoUClQ5x4JdwYB1j9dDh5QSbCv/oWchcAlAd32X5dRCXdS/YY7",
	"HIQ+oM41mkkZio5tLxaLvcX+HuNT22m1j+xsKmHftlGjVsdk3s0R+8TT/QW4ESdyaYuISBD2fCGaTstp",
	"qe43DUQkBNpUuQwBdZCQnNApWjXSB5hzvFT/szUvovEcXFneLvGMM1EcgLEh5CBcTkJJGFUd/sVhgjro",
	"Nztztp142i70XWX2sdiWVQPBXUg4Vu0nWJoXJEJEmLqwtQPwqp2tQ4g84nWSf522s48a1bvOBp3wPavL",
	"KGVclAeYdhRyxiYPOSaLy1B3X09UgNwlcDIheOxDN8NrAw1zXs01PAIYJrs3TcqbogmDJXiog5yW0262",
	"W82WM2ofdn4/6rRaX1EDzRcCdRDM+/x0fkYGwVcxG3869Sdef+4G/uc/5uG4F/Sc027f+9ztz8YfXTIg",
	"/Q9f35+Pzi76b/f2Ruety7Pvx9PZn6OD496l98k9ujo6c/C87XwenM0v/3f5tQ3t/Tenf749c1rwTpwu",
	"L4bzUy8YXYXOp2/e96hLx+ezd5/ueuNT+PC+NxjMjqcoCcgw4iET2gVCKIgw+gXkjHlZUPuC0SsYX5Ap",
	"xTLioAiHGuhWB8HFuSElKP32DZbNVhL9HALXXjNERDvMyK+8uZWhNDSYLL2vA1mPR9MyfdTT06osoBuj",
	"YBzzLmmm8YOkebQJaCQVlKVlW4xQGQCVJgoSOmFqGKbLwQR1rrcTKZ3phEfTnhq5amwfENuQdb8x+IPD",
	"hPj+8S0mPh4Tn8hlbpNjxnzAVemMc2bIRC7ztCsmjAdYog4iVO472e4JlTCNPReAEHgK5shx+B4RrgB1",
	"Hc+Z9Tfto+SckmE4YBGVg8kX8IhLKBiDicPQT2D1QVkA1F0aQRFVWK5a4JgDronHzSOmjMs4v6fZblu8",
	"NbYNJ+OMiZBI7Jv94jFXMl6Nft28zhQXEgehsWO6SuVMPosda2wMVFSUiUISGaluWygXzhitPLEn4CpD",
	"twwXLuNwyWR1H1Ok0rPZ7MWnH+5GdGBJgErzkmPC5czDy8dpGgF3tRavAitQic1gfU1icq1sahEv75cN",
	"kZNNWRI9Oc0zzDu2UXXcbaijutblCoBa6qi8G5U9fb/GEVXWeqXjYYZ9H+i0HgNuGgVhlo1FbgtD2z2C",
	"pnsIh803B28nzbHzu9M8OoAD3ILD/aNDdWS8Ii0XyZlyrbsBkh+Xcm/2HUerOSd2fVEtlM8JvBTJ6bmZ",
	"xrPUGv8aTE6YADPT1j0SIVaaQpKA0OmIjfA3MJzVWzNWyv8LhcckSwLmwI8jOcv+fUi1Sf9qhBpxsaz1",
	"jm7NfKvyC1qtckpNEqmp28WULayT918G1vGwF/tbaKeg9p5WxywEikOCOmh/r7WnBFCI5UybZMdnqrDv",
	"4x89b1UoH/M8arLJBLiwdTyY0MlVRUWHoKeCOmRCnsQTniTT5asmkWWMgZ5KW8JxAFL9UYwmymxlHUrP",
	"DZQahvJCTPIIEm8Z5c1N3BmEfMe8ZSwGqVTaVyWQTFnZcxHDJ5tqo5r9parcIAFhUYg9uuwsilrlS/1A",
	"hIwmXHFarSc4zS3GuVevIlKPvLwERYM/tOyDCY58+Sh7tp0McbVgWC6icBeCK8Gz0j4ZjzU88wy+vlEo",
	"E1EQYL5UPNT5XVjZ5i1NGGvCuJXnlPXvKVBFGxAWtnxCv+kuZ+eWKi7+o5CAldS+RjGJ0I2y40eYel8K",
	"xEo5ZwoG7n6ER1G3WwrxzrjcME7lGgx4ZH74S/H+0AuzurL52dJCA1FGXXjJ1Fxz7yNIA/HGS4t4u6WT",
	"XXylvRNmFd5C/sMxP7dWdYX4wg+TTUDr3OHpc2JKboGWwF4F86RsF/Z9WsB7K9sjntgG12EyaJgOOVED",
	"6oBvvchPREq6u6fpo5cOHuz7lvKENQaf0SmhU0uyBDxJlHKYSSK9DTRV2fFxSKpIfS8HXRsb3wRZdij/",
	"XUBWkLY575Rz1vPC7oE69JdB3nNUofUEpkcec+f1V5SFdd8Fvr7Sj1Ar9ZzKu+WikLPAiqXac/EhJ08f",
	"KPRqc6Obm3GHPHlIff6T8H+VhF+R7ONSa+cZv4jwwl1Hc74QzRAvfYa9ZzoY8uDP34r0F2KYLPSyKPEs",
	"J9GWS5Mf/hZi1+8jx1jAwZv+1cUwA8hrfx35cf2O0cWUUeJi35ovhJVwxGKTPH9TKilaK/oKMqXKL08g",
	"bp6dTxNrefK9MLnWq1Rk61uyys/90i2fxzZVTPXLUK7urfSrUXvZTbiV39+m9CscmYWOCdhiLRjOMA+w",
	"u6ymXNyBgCJd0nk765rJAuIB8q0nHq6nreTfeTplLRqu5/uJ+q0ulV7thZQZc1supdZXUth0KZWC5Omw",
	"tO+NsdleuvwIWIdGCOwQwWb1FlaY8dMqm61a7tXxplzJPMyK8XLdVrhK2j0J7M0v3HbPiI1Pv/7m7Nj0",
	"f319UxRlXRYEyfJbxduFxDIS9T55fg2vEqrkU+7tgYGiFRzUq/PbFKsR95Nvpjq27TMX+zMmZOeodaS/",
	"v1zdrP4fAAD///HMH6ymNAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
