openapi: '3.0.2'
info:
  title: SSI medical prescriptions DEMO API
  version: '1.0'
servers:
  - url: http://localhost:8888
  - url: http://localhost:8989

paths:
  /v1/doctors/{doctorId}/prescriptions/credential-offers/:
    post:
      tags:
        - Doctor
      summary: Creates credential offer for prescription (generates a link for QR code)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: doctorId
          schema:
            type: string
          required: true
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/prescription'
          required: true

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/credentialOfferResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       
          
  /v1/doctors/{doctorId}/prescriptions/credential-offers/{credentialOfferId}:
    get:
      tags:
        - Doctor
      summary: Gets credential offer by id
      parameters:
        - in: path
          name: doctorId
          schema:
            type: string
          required: true
        - in: path
          name: credentialOfferId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCredentialOfferResponse'
                
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       

  /v1/doctors/{doctorId}/prescriptions/credential-offers/{credentialOfferId}/credential:
    get:
      tags:
        - Doctor
      summary: Gets credential issued for given credential offer
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: doctorId
          schema:
            type: string
          required: true
        - in: path
          name: credentialOfferId
          schema:
            type: string
          required: true

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/credentialResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       

  /v1/patients/{patientId}/prescriptions/credentials/:
    post:
      tags:
        - Patient
      summary: Creates credential in response to credential offer from doctor
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: patientId
          schema:
            type: string
          required: true
      requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  credentialOfferId:
                    type: string
                  did:
                    type: string
                  kmsPassphrase:
                    type: string
          required: true

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/credentialResponse'               
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       

  /v1/pharmacies/{pharmacyId}/prescriptions/presentation-requests:
    post:
      tags:
        - Pharmacy
      summary: Creates presentation request for prescription (generates link for a QR code)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pharmacyId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createPresentationRequestResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       

  /v1/pharmacies/{pharmacyId}/prescriptions/presentation-requests/{presentationRequestId}:
    get:
      tags:
        - Pharmacy
      summary: Gets presentation request for prescription by request id
      parameters:
        - in: path
          name: pharmacyId
          schema:
            type: string
          required: true
        - in: path
          name: presentationRequestId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPresentationRequestResponse' 

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       

  /v1/patients/{patientId}/prescriptions/presentations:
    post:
      tags:
        - Patient
      summary: Creates verifiable presentation in response to prescription presentation request from pharmacy
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: patientId
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                presentationRequestId:
                  type: string
                credentialId:
                  type: string
                kmsPassphrase:
                  type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/presentationResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       
            
  /v1/patients/{patientId}/dids:
    get:
      tags:
        - Patient
      summary: Gets all dids belonging to given patient
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: patientId
          schema:
            type: string
          required: true

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/getAllDidsResponse'
                
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'   

  /v1/pharmacies/{pharmacyId}/prescriptions/presentation-requests/{presentationRequestId}/presentation:
    get:
      tags:
        - Pharmacy
      summary: Gets verifiable presentation for given presentation request
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pharmacyId
          schema:
            type: string
          required: true
        - in: path
          name: presentationRequestId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getVerifiablePresentationResponse'
                
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'       

  /v1/patients/{patientId}/prescriptions/credentials/{credentialId}:
    get:
      tags:
        - Patient
      summary: Gets prescription credential by id issued for given patient
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: patientId
          schema:
            type: string
          required: true
        - in: path
          name: credentialId
          schema:
            type: string
          required: true
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/presentationResponse'
                  
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'       

  /v1/patients/{patientId}/prescriptions/credentials:
    get:
      tags:
        - Patient
      summary: Gets all prescription credentials issued for given patient
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: patientId
          schema:
            type: string
          required: true
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/getAllPrescriptionCredentialResponse'
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'         
  
  /v1/vc/verify-credential:
    post:
      tags:
        - Verifiable
      summary: Verify Credential
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credential'
      responses:
          '200':
            description: OK
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'
  
  /v1/vc/verify-presentation:
    post:
      tags:
        - Verifiable
      summary: Verify Credential
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/presentation'
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/verificationResponse'

          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'    

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    credential:
      type: object
      properties:
        '@context':
          type: array
          items:
            type: string
          example: ["https://www.w3.org/2018/credentials/v1", "https://www.w3.org/2018/credentials/examples/v1", "https://w3id.org/security/suites/jws-2020/v1"]
        type:
          type: array
          items:
            type: string
          example: ["VerifiableCredential", "PrescriptionCredential"]
        issuer:
          type: object
          properties:
            id:
              type: string
              example: did:example:123
            name:
              type: string
              example: Dr. Connors
        issuanceDate:
          type: string
        expirationDate:
          type: string
        credentialSubject:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            prescription:
              $ref: '#/components/schemas/prescription'
        proof:
          type: object
          $ref: '#/components/schemas/credentialProof'

    presentation:
      type: object
      properties:
        '@context':
          type: array
          items:
            type: string
          example: ["https://www.w3.org/2018/credentials/v1", "https://www.w3.org/2018/credentials/examples/v1", "https://w3id.org/security/suites/jws-2020/v1"]
        type:
          type: string
          example: "VerifiablePresentation"
        verifiableCredential:
          type: array
          items:
            $ref: '#/components/schemas/credential'
        proof:
          type: array
          items:
            $ref: '#/components/schemas/presentationProof'

    credentialProof:
      type: object
      properties:
        type:
          type: string
          # example: JsonWebSignature2020
        created:
          type: string
          # example: '2021-10-02T17:58:00Z'
        proofPurpose:
          type: string
          # example: assertionMethod
        verificationMethod:
          type: string
          # example: did:example:123#key-0
        jws:
          type: string   
          # example: eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..VA8VQqAerUT6AIVdHc8W8Q2aj12LOQjV_VZ1e134NU9Q20eBsNySPjNdmTWp2HkdquCnbRhBHxIbNeFEIOOhAg
      
      example:
          type: JsonWebSignature2020
          created: '2021-10-02T17:58:00Z'
          proofPurpose: assertionMethod
          verificationMethod: did:example:123#key-0
          jws: ejJrNjQiOmZshbHNlfdJjcmlLKjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..TR0VQqAghUT6AIVdHc8W8Q2aj12LOQjV_VZ1e134NU9Q20eBsNySPjNdmTWp2HkdquCnbRhBHxIbNeFEIOOhAg
      
    presentationProof:
      allOf:
        - $ref: '#/components/schemas/credentialProof'
      example:
        type: JsonWebSignature2020
        created: '2021-10-02T17:58:00Z'
        proofPurpose: authentication
        verificationMethod: did:example:124#key-2
        jws: ejJrNjQiOmZshbHNlfdJjcmlLKjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..TR0VQqAghUT6AIVdHc8W8Q2aj12LOQjV_VZ1e134NU9Q20eBsNySPjNdmTWp2HkdquCnbRhBHxIbNeFEIOOhAg

    
    ointmentDrugInfo:
      type: object
      properties:
        amountOfMedicine:
          type: number
        useArea:
          type: string
        applicationFrequency:
          type: string
        usage:
          type: string

    tabletDrugInfo:
      type: object
      properties:
        numberOfDrug:
          type: number
        numberOfDoses:
          type: string
        daysOfMedication:
          type: number
        timingToTakeMedicine:
          type: string

    drug:
      type: object
      properties:
        drugNumber:
          type: number
        drugName:
          type: string
        drugType:
          type: string
          example: tablet / ointment
        refillAvailability:
          type: boolean
        info:
          type: object
          anyOf:
            - $ref: '#/components/schemas/ointmentDrugInfo'
            - $ref: '#/components/schemas/tabletDrugInfo'
    
    prescription:
      type: object
      properties:
        patientInfo:
          type: object
          properties:
            name:
              type: string
            birthday:
              type: string
            sex:
              type: string
        issuanceInfo:
          type: object
          properties:
            issuanceDate:
              type: string
            expirationDate:
              type: string
        hospitalInfo:
          type: object
          properties:
            location:
              type: string
            hospitalName:
              type: string
            doctorName:
              type: string
            phone:
              type: string
            doctorSignatureStamp:
              type: string
            prefectureNumber:
              type: number
            scoreVoteNumber:
              type: number
            medicalInstitutionNumber:
              type: number
        drugs:
          type: array
          items:
            $ref: '#/components/schemas/drug'

    credentialOfferResponse:
      type: object
      properties:
        credentialOfferId:
          type: string
    
    credentialResponse:
      type: object
      properties:
        credential:
          $ref: '#/components/schemas/credential'
    
    presentationResponse:
      type: object
      properties:
        presentation:
          $ref: '#/components/schemas/presentation'

    getCredentialOfferResponse:
      type: object
      properties:
        prescription:
          $ref: '#/components/schemas/prescription'

    createPresentationRequestResponse:
      type: object
      properties:
        presentationRequestId:
          type: string
  
    getPresentationRequestResponse:
      type: object
      properties:
        presentationRequestId:
          type: string
        challenge:
          type: string

    getAllDidsResponse:
      type: object
      properties:
        dids:
          type: array
          items:
            type: string

    getVerifiablePresentationResponse:
      type: object
      properties:
        presentation:
          $ref: '#/components/schemas/presentation'
        verificationStatus:
          type: boolean
        verificationComment:
          type: string

    getAllPrescriptionCredentialResponse:
      type: object
      properties:
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/credential'
    
    verificationResponse:
      type: object
      properties:
        verified:
          type: boolean

    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message