#
# Copyright IBM Corp, SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  issuer.agent.ssimp.com:
    container_name: issuer.agent.ssimp.com
    image: ${AGENT_REST_IMAGE}:${AGENT_REST_IMAGE_TAG}
    environment:
      - ARIESD_API_HOST=${ISSUER_AGENT_HOST}:${ISSUER_AGENT_API_PORT}
      - ARIESD_INBOUND_HOST=${HTTP_SCHEME}@${ISSUER_AGENT_HOST}:${ISSUER_AGENT_INBOUND_PORT}
      - ARIESD_INBOUND_HOST_EXTERNAL=${HTTP_SCHEME}@http://issuer.agent.ssimp.com:${ISSUER_AGENT_INBOUND_PORT}
      - ARIESD_WEBHOOK_URL=http://example.webhook.com
      - ARIESD_DEFAULT_LABEL=issuer-aries-agent
      - ARIESD_DATABASE_TYPE=leveldb
      - ARIESD_DATABASE_PREFIX=issuer
      - ARIESD_DATABASE_TIMEOUT=60
      - ARIESD_HTTP_RESOLVER=${HTTP_DID_RESOLVER}
      - ARIESD_CONTEXT_PROVIDER_URL=${CONTEXT_PROVIDER_URL}
      - ARIESD_MEDIA_TYPE_PROFILES=${DEFAULT_MEDIA_TYPE_PROFILES}
      - ARIESD_KEY_TYPE=${DEFAULT_KEY_TYPE}
      - ARIESD_KEY_AGREEMENT_TYPE=${DEFAULT_KEY_AGREEMENT_TYPE}
    ports:
      - ${ISSUER_AGENT_INBOUND_PORT}:${ISSUER_AGENT_INBOUND_PORT}
      - ${ISSUER_AGENT_API_PORT}:${ISSUER_AGENT_API_PORT}
    command: "start"
    networks:
      - ssimp_demo_net
    depends_on:
      - file-server.example.com
  
  holder.agent.ssimp.com:
    container_name: holder.agent.ssimp.com
    image: ${AGENT_REST_IMAGE}:${AGENT_REST_IMAGE_TAG}
    environment:
      - ARIESD_API_HOST=${HOLDER_AGENT_HOST}:${HOLDER_AGENT_API_PORT}
      - ARIESD_INBOUND_HOST=${HTTP_SCHEME}@${HOLDER_AGENT_HOST}:${HOLDER_AGENT_INBOUND_PORT}
      - ARIESD_INBOUND_HOST_EXTERNAL=${HTTP_SCHEME}@http://holder.agent.ssimp.com:${HOLDER_AGENT_INBOUND_PORT}
      - ARIESD_WEBHOOK_URL=http://example.webhook.com
      - ARIESD_DEFAULT_LABEL=holder-aries-agent
      - ARIESD_DATABASE_TYPE=leveldb
      - ARIESD_DATABASE_PREFIX=holder
      - ARIESD_DATABASE_TIMEOUT=60
      - ARIESD_HTTP_RESOLVER=${HTTP_DID_RESOLVER}
      - ARIESD_CONTEXT_PROVIDER_URL=${CONTEXT_PROVIDER_URL}
      - ARIESD_MEDIA_TYPE_PROFILES=${DEFAULT_MEDIA_TYPE_PROFILES}
      - ARIESD_KEY_TYPE=${DEFAULT_KEY_TYPE}
      - ARIESD_KEY_AGREEMENT_TYPE=${DEFAULT_KEY_AGREEMENT_TYPE}
    ports:
      - ${HOLDER_AGENT_INBOUND_PORT}:${HOLDER_AGENT_INBOUND_PORT}
      - ${HOLDER_AGENT_API_PORT}:${HOLDER_AGENT_API_PORT}
    command: "start"
    networks:
      - ssimp_demo_net
    depends_on:
      - file-server.example.com
  
  verifier.agent.ssimp.com:
    container_name: verifier.agent.ssimp.com
    image: ${AGENT_REST_IMAGE}:${AGENT_REST_IMAGE_TAG}
    environment:
      - ARIESD_API_HOST=${VERIFIER_AGENT_HOST}:${VERIFIER_AGENT_API_PORT}
      - ARIESD_INBOUND_HOST=${HTTP_SCHEME}@${VERIFIER_AGENT_HOST}:${VERIFIER_AGENT_INBOUND_PORT}
      - ARIESD_INBOUND_HOST_EXTERNAL=${HTTP_SCHEME}@http://verifier.agent.ssimp.com:${VERIFIER_AGENT_INBOUND_PORT}
      - ARIESD_WEBHOOK_URL=http://example.webhook.com
      - ARIESD_DEFAULT_LABEL=holder-aries-agent
      - ARIESD_DATABASE_TYPE=leveldb
      - ARIESD_DATABASE_PREFIX=verifier
      - ARIESD_DATABASE_TIMEOUT=60
      - ARIESD_HTTP_RESOLVER=${HTTP_DID_RESOLVER}
      - ARIESD_CONTEXT_PROVIDER_URL=${CONTEXT_PROVIDER_URL}
      - ARIESD_MEDIA_TYPE_PROFILES=${DEFAULT_MEDIA_TYPE_PROFILES}
      - ARIESD_KEY_TYPE=${DEFAULT_KEY_TYPE}
      - ARIESD_KEY_AGREEMENT_TYPE=${DEFAULT_KEY_AGREEMENT_TYPE}
    ports:
      - ${VERIFIER_AGENT_INBOUND_PORT}:${VERIFIER_AGENT_INBOUND_PORT}
      - ${VERIFIER_AGENT_API_PORT}:${VERIFIER_AGENT_API_PORT}
    command: "start"
    networks:
      - ssimp_demo_net
    depends_on:
      - file-server.example.com

  couchdb.example.com:
    container_name: couchdb.example.com
    image: ${COUCHDB_IMAGE}:${COUCHDB_IMAGE_TAG}
    ports:
      - ${COUCHDB_PORT}:${COUCHDB_PORT}
    environment:
      - COUCHDB_USER=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./couchdb-config/10-single-node.ini:/opt/couchdb/etc/local.d/config.ini
    networks:
      - ssimp_demo_net

  file-server.example.com: # file server for hosting static resources (e.g. JSON-LD contexts)
      container_name: file-server.example.com
      image: halverneus/static-file-server:latest
      environment:
        - PORT=9099
        - FOLDER=/data
      ports:
        - "9099:9099"
      volumes:
        - ./data:/data
      networks:
        - ssimp_demo_net

networks:
  ssimp_demo_net:
    driver: bridge
